export * from './email-adapter.interface';
export * from './email-attachment.interface';
export * from './email-send-error.interface';
export * from './email-send-options.interface';
export * from './email-send-result.interface';
export * from './aws-ses-config.interface';
export * from './resend-config.interface';
export * from './email-module-config.interface';
export * from './global-email-settings.interface';
